In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [15]:
#1
import numpy as np
a=np.random.randint(1,11,size=10)
b=np.random.randint(1,11,size=10)
print(a)
print(b)

[ 4  2 10  3  6  3  9  6  5  5]
[ 1  5  3  5  7  7  2  9  6 10]


In [16]:
sum=a+b
sum

array([ 5,  7, 13,  8, 13, 10, 11, 15, 11, 15])

In [19]:
sum.reshape((2,5))

array([[ 5,  7, 13,  8, 13],
       [10, 11, 15, 11, 15]])

In [20]:
sum.mean()

10.8

In [68]:
#2
arr=np.random.randint(10,size=(3,3))
arr

array([[2, 0, 2],
       [9, 3, 3],
       [0, 8, 7]])

In [69]:
arr[0]

array([2, 0, 2])

In [71]:
arr[:,0]

array([2, 9, 0])

In [31]:
arr.reshape((9,1))

array([[3],
       [6],
       [9],
       [7],
       [5],
       [7],
       [9],
       [8],
       [4]])

In [32]:
arr.flatten()

array([3, 6, 9, 7, 5, 7, 9, 8, 4])

In [42]:
#3
arr2=np.random.randint(1,11,size=(4,3))
arr2

array([[ 4,  6,  1],
       [ 9,  1,  2],
       [ 2, 10,  2],
       [ 9,  6,  5]])

In [64]:
np.vstack(arr2[:,2])

array([[1],
       [2],
       [2],
       [5]])

In [45]:
#4
ar=np.random.randint(1,30,size=9)
ar

array([ 3, 17, 24, 18, 24, 13,  9, 18, 15])

In [47]:
ar[2]

24

In [46]:
ar.max()

24

In [51]:
#5
x=np.random.randint(1,5,size=(2,2))
y=np.random.randint(1,5,size=(2,2))
print(x)
print(y)

[[4 2]
 [3 1]]
[[3 2]
 [2 1]]


In [60]:
x_T=x.transpose()
x_T

array([[4, 3],
       [2, 1]])

In [59]:
sum=x_T+y
sum

array([[7, 5],
       [4, 2]])